spring:
  application:
    name: hackaton

  # PostgreSQL Database (JDBC)
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  # Redis (for caching if needed)
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_HOST}

  # Jackson
  jackson:
    serialization:
      write-dates-as-timestamps: false

# Telegram Bot Configuration
telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}
    proxy-url: ${TELEGRAM_PROXY_URL:}
